# Generated by Django 5.2.7 on 2025-11-08 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='device',
        ),
        migrations.AddField(
            model_name='logentry',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_logs', to='monitor.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='sender',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sent_logs', to='monitor.device'),
            preserve_default=False,
        ),
    ]
